### ISSUE TITLE
IPSec support exists in OpnSense

### ISSUE THREAD

**Issue by telmich** [O-X-L/ansible-opnsense#1]
I saw your forum thread before of missing IPSec support, but it seems from the API documentation, that IPSec via API could be supported:

https://docs.opnsense.org/development/api/core/ipsec.html

On a side note, do you know how much effort it would be to implement the quagga API (https://docs.opnsense.org/development/api/plugins/quagga.html) in the ansible collection, too?

**Comment by ansibleguy** [comment]
Greetings!

The problem of the IPSec API-endpoint is that currently one cannot add/update phase 1 and phase 2 tunnels/configs.
The [endpoint model](https://raw.githubusercontent.com/opnsense/core/master/src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml) only includes options to manage key-pairs (_certificate authentication_) and pre-shared-keys.
Therefore it is not very useful as of now.

\- AnsibleGuy
