### ISSUE TITLE
Problem: [bind_record] Validation of MX records is wrong

### ISSUE THREAD

**Issue by FSeidinger-XI** [O-X-L/ansible-opnsense#105]
### Modules

ansibleguy.opnsense.bind_record

### Version

```bash
1.2.10
```

### Ansible Version

```bash
ansible [core 2.17.4]
  config file = /etc/ansible/ansible.cfg
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
  jinja version = 3.1.4
  libyaml = True
```

### OPNSense Version

```bash
24.7.5_3
```

### OPNSense-Plugin Version

```bash
os-bind (installed) 1.32_1
```

### Issue

A typical apex of an ISC bind zone file according to the ISC documentation looks like that:

```Text
@         IN      SOA   ns1.example.com. hostmaster.example.com.
          IN      NS      ns1.example.com.
3w        IN      MX  10  mail.example.com.
          IN      MX  20  mail.example.net.
```

Where records are made of columns separated by spaces. In case of an MX record there are four columns:

| Column | Required | Example | Description
| - | - | - | - |
| ttl | no | 1w | TTL for our MX record. Which means any SMTP server or any DNS client, who caches the output should only cache it till one week. After this cache expiry of 1 week, the DNS client should re-fetch it again from the DNS server of the domain. If you do not give this ttl value the MX record will take the default ttl value of the domain |
| class | yes | MX | The class of the record. Must be MX |
| preference | no | 10 | Preference value for this MX record. A lower number means high preference |
| name | yes | mail.example.org. | FQDN of our mail server.<br><br>This FQDN should have an A record, in the zone file (if its part of the same zone). This is the reason we have an A record, for mail.example.com inside our example.com zone file shown above.<br><br>If its not part of the same zone (for example, you have given your mail server as something like mail.example.net or mail.anything.com), then that name should be resolvable to an IP address (A record) externally<br><br>Notice that the name must end with a dot because it should not be appended by search domains |

On the GUI there are no validations and therefor you can use the name field for the ttl, the type is a select box, the value can be the combined value for preference and name.

The ansible module has two bugs in that way:

1. The value is checked by the code to be a host name. The regex does not allow for a trailing dot as required by spec.
2. The value cannot not be combined with a preference, because that is also not covered by the regex for hostname validation.

### Debug Output

```bash
Case 1 - FAILED! => {"changed": false, "msg": "Value 'mail.example.org.' is not a valid hostname!"}
Case 2 - FAILED! => {"changed": false, "msg": "Value '10 mail.example.org.' is not a valid hostname!"}
```

**Comment by ansibleguy** [comment]
Should now be fixed on latest - feel free to test it and report back if there are any issues with it:
`ansible-galaxy collection install git+https://github.com/ansibleguy/collection_opnsense.git`
