### ISSUE TITLE
Hostnames without a dot like "router" are not accepted

### ISSUE THREAD

**Issue by telmich** [O-X-L/ansible-opnsense#2]
When trying to connect to IPv6 only hosts, it seems that this module fails with being unable to resolve the domain name. Example below for the host "rmrouter1", which is reachable at OS level:

```
TASK [Tmux] *************************************************************************************
fatal: [router1]: FAILED! => {"changed": false, "msg": "Host 'rmrouter1' is neither a valid IP nor Domain-Name!"}

PLAY RECAP **************************************************************************************
router1                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

[10:50] nb3:rulematch-ansible% ping -c1 rmrouter1
PING rmrouter1(rmrouter1 (2a0a:e5c0:10:bee::1001)) 56 data bytes
64 bytes from rmrouter1 (2a0a:e5c0:10:bee::1001): icmp_seq=1 ttl=61 time=39.0 ms

--- rmrouter1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 38.956/38.956/38.956/0.000 ms
[10:50] nb3:rulematch-ansible% 
```

The name is configured in the hosts file:

```
nb3:~# grep rmrouter1 /etc/hosts
2a0a:e5c0:10:bee::1001 rmrouter1
```

**Comment by telmich** [comment]
Checking the code:

```
def check_host(module: AnsibleModule) -> None:
    if not is_ip(module.params['firewall']) and not domain(module.params['firewall']):
        module.fail_json(f"Host '{module.params['firewall']}' is neither a valid IP nor Domain-Name!")
```

domain() seems to be imported from the [validators package](https://validators.readthedocs.io/en/latest/).

That code seems to check for a dot in the name:

```
>>> import validators
>>> validators.domain("router1")
ValidationFailure(func=domain, args={'value': 'router1'})
>>> validators.domain("router1.local")
True
>>> 
```

And does not actually do any resolution. Instead of doing these checks, I would recommend to try to connect to it and then use that failure. Neither `is_ip` nor `domain` will answer the question to "can I potentially connect to it".

It seems just replacing the `check_host` code with `return None` is not good enough to convince the collection to connect nonetheless, it seems I am missing the correct call path.

**Comment by ansibleguy** [comment]
Hi.
Thanks for reporting this problem.

To clarify: this is thought to be a 'quick' validation if the firewall-host value is legit.
The connection will fail later on if the target isn't reachable (_while initiating the first connection_).
Therefore another connection-test would be unneeded overhead in my opinion.

\- AnsibleGuy
