### ISSUE TITLE
FRR - General setting configuration is missing

### ISSUE THREAD

**Issue by itmwiw** [O-X-L/ansible-opnsense#26]
FRR can be configured globally before configuring each routing protocol. For example, you can enable it or activate CARP Failover:
<img width="749" alt="opnsense-frr" src="https://github.com/ansibleguy/collection_opnsense/assets/84352276/07a53162-3eec-48d7-acb8-30fb0deca603">
This is missing in the collection.

**Comment by ansibleguy** [comment]
Thanks for informing me.
Seems I've forgotten to implement [this API endpoint](https://github.com/opnsense/plugins/blob/master/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml)

**Comment by ansibleguy** [comment]
Here you go: [ansibleguy.opnsense.frr_general](https://opnsense.ansibleguy.net/en/latest/modules/frr_general.html)

**Comment by itmwiw** [comment]
Thanks a lot!
