### ISSUE TITLE
Problem: interface_vip error 'A network address is required'

### ISSUE THREAD

**Issue by rostchri** [O-X-L/ansible-opnsense#34]
### Modules

ansibleguy.opnsense.interface_vip

### Version

1.2.7

### Ansible Version

2.14.2

### OPNSense Version

23.7.8_1

### OPNSense-Plugin Version

os-firewall:  1.4_2

### Issue

I'm using the following ansible task:

<code>
- name: Ensure existence of Virtual IP adress
  ansibleguy.opnsense.interface_vip:
    description: Test
    interface: wan
    address: xyz.178.77.182
    cidr: 27
</code>

and got the response  'A network address is required.' 
I think address and cidr should be enough to get this ip-alias working.

### Config Ansible

<code>
[defaults]
callback_plugins= ./callbacks
stdout_callback = anstomlog
retry_files_enabled = False
collections_paths = collections
</code>

### Config OPNSense

root@OPNsense:~ # ifconfig wan

<code>
wan: flags=8863<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: WAN (wan)
        options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
        ether 0c:70:51:ec:00:01
        inet6 fe80::e70:51ff:feec:1%wan prefixlen 64 scopeid 0x2
        inet xyz.178.77.173 netmask 0xffffffe0 broadcast xyz.178.77.191
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
</code>

### Debug Output

<code>
vhpfwnat-gns3-01` | FAILED | 826ms
{
  - msg: API call failed | Error: {'vip.network': ['A network address is required.']} | Response: {'status_code': 200, 'headers': Headers({'content-type': 'application/json; charset=UTF-8', 'content-length': '84', 'date': 'Fri, 24 Nov 2023 13:17:32 GMT', 'server': 'OPNsense'}), '_request': <Request('POST', 'https://localhost:20080/api/interfaces/vip_settings/addItem')>, 'next_request': None, 'extensions': {'http_version': b'HTTP/1.1', 'reason_phrase': b'OK', 'network_stream': <httpcore._backends.sync.SyncStream object at 0x1055d7010>}, 'history': [], 'is_closed': True, 'is_stream_consumed': True, 'default_encoding': 'utf-8', 'stream': <httpx._client.BoundSyncStream object at 0x1055d7150>, '_num_bytes_downloaded': 84, '_decoder': <httpx._decoders.IdentityDecoder object at 0x105843d90>, '_elapsed': datetime.timedelta(microseconds=32617), '_content': b'{"result":"failed","validations":{"vip.network":["A network address is required."]}}'}
  - changed: False
}
</code>

**Comment by ansibleguy** [comment]
Related to: https://github.com/opnsense/core/issues/7041

**Comment by fichtner** [comment]
Automatically adding /32 or /128 to the address is no longer supported in 23.7.9. These subnet sizes are also likely wrong to begin with. This works as intended now.

**Comment by ansibleguy** [comment]
@rostchri The issue should be fixed in the latest version:

`ansible-galaxy collection install git+https://github.com/ansibleguy/collection_opnsense.git`

Thank you for opening the issue!

**Comment by ansibleguy** [comment]
Also related: https://github.com/ansibleguy/collection_opnsense/commit/3a824c29df3720de7a30d8087ace266ca9707716
