### ISSUE TITLE
how to set a DHCP Static Mapping

### ISSUE THREAD

**Issue by cchalifo999** [O-X-L/ansible-opnsense#35]
how to set DHCP Static Mappings

**Comment by ansibleguy** [comment]
Greetings!

There is no way to do this right now, because [no API has been implemented by OPNSense](https://docs.opnsense.org/development/api/core/dhcp.html)

**Comment by cchalifo999** [comment]
ty

**Comment by ansibleguy** [comment]
FYI: I opened a feature-request at the OPNSense repo - https://github.com/opnsense/core/issues/7108
