### ISSUE TITLE
Enable wireguard via ansible is missing [general tab]

### ISSUE THREAD

**Issue by telmich** [O-X-L/ansible-opnsense#4]
The wireguard VPN menu has multiple tabs, local + endpoints are supported with the current implementation, however the "enable wireguard" on the "General" tab in the beginning seems not to be supported.

![2022-10-30-154024_614x293_scrot](https://user-images.githubusercontent.com/9397/198884658-8d38b137-747a-44f2-ad19-468d7ccd5680.png)

**Comment by ansibleguy** [comment]
Greetings!

It's now implemented as of commit 014edb4ab660fe7bf07464545fa7182f874cd7a2.

\- AnsibleGuy
