### ISSUE TITLE
Feature: DHCP leases

### ISSUE THREAD

**Issue by david-sieg** [O-X-L/ansible-opnsense#45]
### Link to API

https://docs.opnsense.org/development/api/core/dhcp.html

### Description

It would be nice to get actual leases from OPNSense.

**Comment by ansibleguy** [comment]
Greetings!

The API docs are missing some information I need to implement it.

As seen in the OPNSense issue https://github.com/opnsense/core/issues/7108 the new/full DHCP API should become available in the next few months. After that I will implement it as Ansible modules (hope I find time for it).

**Comment by ansibleguy** [comment]
https://docs.opnsense.org/development/api/core/kea.html

**Comment by KalleDK** [comment]
@ansibleguy hi - I'm trying to implement this, but I face a problem.
If you want to create a reservation, you need to provide the subnet uuid under the subnet field, but when you search it returns the subnet cidr in that field.

When you create
```json
{
  "subnet": "e134f1c1-a83a-4a2e-aebe-8a786702e52b",
  "ip_address": "172.20.123.12",
  "hw_address": "aa:aa:aa:aa:aa:aa",
  "hostname": "flaf",
  "description": ""
}
```

What search returns
```json
{
  "rows": [
    {
      "uuid": "5beb2a54-f98f-4a44-83ae-c7812a755ca5",
      "subnet": "172.20.123.0/24",
      "ip_address": "172.20.123.12",
      "hw_address": "aa:aa:aa:aa:aa:aa",
      "hostname": "flaf",
      "description": ""
    }
  ]
}
```
Worse yet is the detail request, that returns 

```json
{
    "reservation": {
        "subnet": {
            "6bef2666-20b4-46fd-99fd-3d2c0b205b92": {
                "value": "172.20.10.0\\/24",
                "selected": 0
            },
            "dcc79bb6-d295-4c6b-9142-16fe3c1b1297": {
                "value": "172.20.30.0\\/24",
                "selected": 0
            },
            "e134f1c1-a83a-4a2e-aebe-8a786702e52b":{
                "value":"172.20.123.0\\/24",
                "selected":1
            }
        },
        "ip_address":"172.20.123.12",
        "hw_address":"aa:aa:aa:aa:aa:aa",
        "hostname":"flaf",
        "description":""
    }
}
```

I can do the replace a users input of 172.20.123.0/24 with the uuid in the check method, thereby creating a resservation works..

But if you run again, then i thinks it changed as the search gives the 172.20.123.0/24, but I've just replaced that with the uuid in the check.. Hope it makes sense

https://github.com/KalleDK/collection_opnsense/commit/dfbe0b2dbe9d0c873766c194b2df976edc6a8128

Bonus fun fact.. the subnet is not really an identifier, as it's legal to have the same subnet multiple times in the config.. But I got no good way of identifying them

**Comment by ansibleguy** [comment]
@KalleDK Thank you for starting! I've updated the implementation and it's available in this latest branch.
Please test it and report back if something is misbehaving => `ansible-galaxy collection install git+https://github.com/ansibleguy/collection_opnsense.git`
Thank you

**Comment by ansibleguy** [comment]
1h 30m

**Comment by KalleDK** [comment]
@ansibleguy looks good to me - though I don't know if the `FIELDS_IGNORE = ['subnet']  # empty field ?!` is needed? Didn't seem to have any effect when I tested

**Comment by KalleDK** [comment]
@ansibleguy I'm also looking at adding subnets, they have a nested dict with "extra" options. Is there another module with that? Can't seem to find any.

**Comment by KalleDK** [comment]
I would love to continue on this, but I'm stuck at the extra dict @ansibleguy  :)

**Comment by ansibleguy** [comment]
Alright - I see.
I think we had the same nested-data issue with the webproxy:
* Handle the nested values manually
  * [when reading](https://github.com/ansibleguy/collection_opnsense/blob/latest/plugins/module_utils/main/webproxy_general.py#L68)
  * [when writing](https://github.com/ansibleguy/collection_opnsense/blob/latest/plugins/module_utils/main/webproxy_general.py#L90)

Related: https://github.com/ansibleguy/collection_opnsense/issues/106

**Comment by ansibleguy** [comment]
I'll close this issue as the dhcp-leases/-reservations are implemented.
Feel free to open a PR or issue for the subnets.

**Comment by ansibleguy** [comment]
Have created a new issue for the subnet-module: https://github.com/ansibleguy/collection_opnsense/issues/127
