### ISSUE TITLE
Feature: Trigger HA-Sync

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/ansible-opnsense#49]
### Link to API

Does not exist - as far as I've seen.
But It would be very useful IF it can be done using the api-key auth..

### Description

The action performed by the button at `System - High Availibility - Status`

The call seems to be very simple:
`https://<fw>/status_habackup.php` with form-data `exec_sync`

Could be used like `reload` - after some changes we want to perform a config-sync.
As a workaround: Currently one can use a cron-job to schedule the config-sync

**Comment by ansibleguy** [comment]
Sorry - but no time for such an no-api feature
