### ISSUE TITLE
Feature: Device name for VLAN interface

### ISSUE THREAD

**Issue by Low-Frequency** [O-X-L/ansible-opnsense#54]
### Link to API

https://docs.opnsense.org/development/api/core/interfaces.html#id4

### Description

When creating VLAN interfaces I noticed the device name being auto generated to "vlan01", "vlan02", ...
This is a bit confusing when you're not creating VLANs with consecutive tags, so you're ending up with:

- vlan01 -> tag 27
- vlan02 -> tag 52

This makes managing the VLANs unnecessary complicated.
From my understanding of the API documentation this feature should be already present in the API and therefore also be implemented in the collection.

As a workaround for now renaming the interfaces manually is possible, but kind of defeats the purpose of automation.

**Comment by ansibleguy** [comment]
Sure - makes sense 👍🏼 
If no name was provided by the user - should we go with `vlan0.<VLAN>`?
Requirements for naming: `...start of the name matches the required prefix and contains numeric characters or dots, e.g. "vlan0.1.2" or "qinq0.3.4".`

Per example: `vlan22` is not a valid name :(
`Only a maximum of 15 characters is allowed starting with "vlan0" combined with numeric characters and dots, e.g. "vlan0.1.104".`

**Comment by Low-Frequency** [comment]
The weird thing is that the web interface doesn't accept `vlan01` as a valid device name, but still auto generates this name if the device name is left empty.

I don't know the inner workings of the module since I haven't looked into the code, so sadly I can't provide a full solution to this (Also, I'm bad at python :laughing:). However there are two options I can propose:
1. If you always use the full configuration as the payload for the API `vlan0.<VLAN>` would be the best option. Also this would be the way to go to comply to the naming scheme.
2. If you generate the payload based on the options provided in the module I'd leave it as is (auto generated to `vlan01`), even if this doesn't comply to the naming scheme. This would be a bit more pleasant for people who already use the module since there won't be any changes they'll have to make.

I guess the API call will fail if `vlan01` is used as the device name in the payload. With that in mind the second option would be the way to go in my opinion, provided the way you handle the payload allows that.
If you go with option 1, people who already use the module will have to change the name of all their VLAN devices, which will be pretty annoying if the devices are already assigned to an interface. Until all devices comply with the naming scheme the module will always fail in that case.

**Comment by ansibleguy** [comment]
The behavior on the latest version is naming it `vlan0.<VLAN>` - you can try that:
`ansible-galaxy collection install git+https://github.com/ansibleguy/collection_opnsense.git`

FYI - the relevant code for VLANs is basically in those two two files:
* https://github.com/ansibleguy/collection_opnsense/blob/latest/plugins/modules/interface_vlan.py
* https://github.com/ansibleguy/collection_opnsense/blob/latest/plugins/module_utils/main/interface_vlan.py
