### ISSUE TITLE
Problem: Upgrade doesn't actually upgrade

### ISSUE THREAD

**Issue by lakotajames** [O-X-L/ansible-opnsense#59]
### Modules

ansibleguy.opnsense.system

### Version

```bash
1.2.8
```

### Ansible Version

```bash
2.12.5.post0
```

### OPNSense Version

```bash
22.7_4
```

### Issue

I want to upgrade the opnsense version.  The task runs successfully, but I'm still on the old version.

### Config Ansible

```yaml
- name: Run audit
      ansibleguy.opnsense.system:
        action: 'audit'
    - name: Pull updates
      ansibleguy.opnsense.system:
        action: 'update'
    - name: Start upgrade - will wait until finished
      ansibleguy.opnsense.system:
        action: 'upgrade'
        timeout: 240  # depends on your download speed and firmware-version
```

### Debug Output

```bash
TASK [Run audit] ***************************************************************
changed: [unclebob]
TASK [Pull updates] ************************************************************
changed: [unclebob]
TASK [Start upgrade - will wait until finished] ********************************
[WARNING]: 2024-03-06 21:11:42 | Waiting download & upgrade to finish..
[WARNING]: 2024-03-06 21:12:27 | Got response!
changed: [unclebob]
```

**Comment by ansibleguy** [comment]
Greetings!

The API endpoint is a little inconsistent, yes.
In my experience it helps to put a few seconds of wait-time between the Update and Upgrade commands.

My test-box is auto-upgraded since +1 year now only using the test-tasks: https://github.com/ansibleguy/collection_opnsense/blob/latest/tests/system.yml

Could you try that? I will update the docs to include this information.

**Comment by lakotajames** [comment]
After adding the wait-time, and running the playbook twice, it upgraded. It did not wait for the reboot after the second run, and continued running the next parts of the playbook (successfully). I'm now running the playbook a third time (because the firewall is still behind), and the upgrade started, but it hasn't even got to the reboot part and the playbook is already finished, successfully running steps after the upgrade that hasn't finished. 

I'm not doing the manual reboot step, will that wait for the upgrade to finish before it starts the reboot?

**Comment by ansibleguy** [comment]
@lakotajames You are right. I've enhanced the system-action handling to:
* Check for the actual update/upgrade status (like the WebUI does)
* Output the status once done

I would be glad if you could test it with the latest version and give some feedback:
`ansible-galaxy collection install git+https://github.com/ansibleguy/collection_opnsense.git`
