### ISSUE TITLE
Feature: support openvpn instances 

### ISSUE THREAD

**Issue by markuman** [O-X-L/ansible-opnsense#74]
### Link to API

https://docs.opnsense.org/development/api/core/openvpn.html#id3

### Description

openvpn servers are marked as legacy. openvpn instances is the new way. It would be nice to have a module that supports openvpn instances.

**Comment by superstes** [comment]
As I see it - the current one uses the instances API: https://github.com/ansibleguy/collection_opnsense/blob/latest/plugins%2Fmodule_utils%2Fmain%2Fopenvpn_server.py#L20

The modules are only called server/client as they differ strongly in their parameters and this makes validation a lot easier.

Instances were also mentioned in the feature: https://github.com/ansibleguy/collection_opnsense/issues/30

**Comment by ansibleguy** [comment]
Yes - we are already using the `instances` API.
As the instance needs to be [either of type](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.xml#L150) `client` or `server` I implemented a logical split between them - in the form of two modules
