### ISSUE TITLE
Feature: Support aliases for ports definition in ansibleguy.opnsense.rule and _multi

### ISSUE THREAD

**Issue by kepi** [O-X-L/ansible-opnsense#86]
### Link to API

https://docs.opnsense.org/development/api/core/firewall.html

### Description

Since at least 24.7 it is possible to specify aliases for ports which is huge help in rules definition.

For impatients: as a workaround, you can just commented try/except in `validate_port` function in `plugins/module_utils/helper/main.py`.

**Comment by ansibleguy** [comment]
Thanks for the info. Have not yet found time to look into the changes.. :/

**Comment by ansibleguy** [comment]
Fix: https://github.com/ansibleguy/collection_opnsense/commit/6bdb61ada8b90cd4593dbac6231078890f748e87
