### ISSUE TITLE
Docs: Remove mentions of os-firewall plugin for recent OPNsense

### ISSUE THREAD

**Issue by kepi** [O-X-L/ansible-opnsense#87]
### Reference

https://opnsense.ansibleguy.net/en/latest/modules/rule.html

### Problem Found

os-firewall is now part of core and you can't install it. It is still mentioned in OPNSense documentation, but there is no such plugin at least since 24.7 (probably since 24.1).

**Comment by ansibleguy** [comment]
Thanks
